### ISSUE TITLE
Skipping tests from fixtures

### ISSUE THREAD

**Issue by antonyc** [rekby/fixenv#10]
Hi! Thanks for the code! It could be useful to have an ability to skip tests from fixture, like callling `Env.Skip()`. There is no way to do that using type casting:
`env.go:79: failed to call fixture func: unexpected exit from function`. This is what I get when I try to call `t.Skip()`

**Comment by rekby** [comment]
Hello.

Can you describe your case with more details:
1. Why you need skip test from fixture, not from test code?
2. Do you need skip all tests for same fixenv scope (may engine cache skip answer similar to any other answer) in your case?

**Comment by antonyc** [comment]
1. Well if I for example create a database cluster in fixture, I would like to skip test that uses this fixture if `short` flag is `on`. 
2. Yes, I would like to skip all tests from scope.

**Comment by rekby** [comment]
I will add skip test by return special error: ErrSkipTest.

**Comment by rekby** [comment]
Done
